### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Blurazzle**
Please update for Laravel 8

### CODE REVIEW

**Comment by Blurazzle** [comment]
Please, can you enable this upgrade to laravel 8.0

**Comment by bennettblack** [comment]
@cooperl22 Is there any way we can get this merged in? Trying to upgrade to Laravel 8 without forking your package.

**Comment by Blurazzle** [comment]
@bennettblack I did fork this repository and the DB2 driver (not on GitHub).

I'm really thankful for the work that has gone into making DB2 and the ToolKit working in Laravel, but the responsiveness of this project on feature suggestions and pull request are simply to slow for us.

**Comment by nathanphelps** [comment]
@wjonkerhulst, would you have any interest in teaming up with @bennettblack and I and forking and maintaining the db2/ibmi packages with us?  Our company can provide sponsorship of the project.

**Pull request closed without merging**
